// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cdvjntncmtmzrbturxuy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkdmpudG5jbXRtenJidHVyeHV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1OTI5MjYsImV4cCI6MjA2MTE2ODkyNn0.U-PcgIq20adJ1j1GEon3A8UbMFQRWBZVbh-WoAZ4_qQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);